name: CI

on:
  push:
    branches: main
  pull_request:
    branches: "*"

jobs:
  rails-test:
    name: Ruby ${{ matrix.ruby }}, Rails ${{ matrix.rails }}

    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.2", "head"]
        rails: ["7.0", "main"]
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: ${{ matrix.rails }}
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Generate lockfile
        run: bundle lock
      - name: Load cached dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('Gemfile.lock') }}
      - name: Install dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run migrations
        run: bundle exec rake db:create db:migrate
      - name: Run tests
        run: bundle exec rails test
